preco = int(input(""))
a = preco / 1
b = preco / 2
c = preco / 3
d = preco / 4
e = preco / 5
f = preco / 6
g = preco / 7
h = preco / 8
i = preco / 9
j = preco / 10
k = preco / 11
l = preco / 12
m = preco / 13
n = preco / 14
o = preco / 15
p = preco / 16
q = preco / 17
r = preco / 18
s = preco / 19
t = preco / 20
u = preco / 21
v = preco / 22
w = preco / 23
z = preco / 24
preco_a = "1x de R$ {preco:.2f}"
preco_b = "2x de R$ {preco:.2f}"
preco_c = "3x de R$ {preco:.2f}"
preco_d = "4x de R$ {preco:.2f}"
preco_e = "5x de R$ {preco:.2f}"
preco_f = "6x de R$ {preco:.2f}"
preco_g = "7x de R$ {preco:.2f}"
preco_h = "8x de R$ {preco:.2f}"
preco_i = "9x de R$ {preco:.2f}"
preco_j = "10x de R$ {preco:.2f}"
preco_k = "11x de R$ {preco:.2f}"
preco_l = "12x de R$ {preco:.2f}"
preco_m = "13x de R$ {preco:.2f}"
preco_n = "14x de R$ {preco:.2f}"
preco_o = "15x de R$ {preco:.2f}"
preco_p = "16x de R$ {preco:.2f}"
preco_q = "17x de R$ {preco:.2f}"
preco_r = "18x de R$ {preco:.2f}"
preco_s = "19x de R$ {preco:.2f}"
preco_t = "20x de R$ {preco:.2f}"
preco_u = "21x de R$ {preco:.2f}"
preco_v = "22x de R$ {preco:.2f}"
preco_w = "23x de R$ {preco:.2f}"
preco_z = "24x de R$ {preco:.2f}"
print(preco_a. format(preco = a))
print(preco_b. format(preco = b))
print(preco_c. format(preco = c))
print(preco_d. format(preco = d))
print(preco_e. format(preco = e))
print(preco_f. format(preco = f))
print(preco_g. format(preco = g))
print(preco_h. format(preco = h))
print(preco_i. format(preco = i))
print(preco_j. format(preco = j))
print(preco_k. format(preco = k))
print(preco_l. format(preco = l))
print(preco_m. format(preco = m))
print(preco_n. format(preco = n))
print(preco_o. format(preco = o))
print(preco_p. format(preco = p))
print(preco_q. format(preco = q))
print(preco_r. format(preco = r))
print(preco_s. format(preco = s))
print(preco_t. format(preco = t))
print(preco_u. format(preco = u))
print(preco_v. format(preco = v))
print(preco_w. format(preco = w))
print(preco_z. format(preco = z))

